<a href="https://colab.research.google.com/github/AkhilGangan/MSC_FDS_530/blob/main/FDS_PRACS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [5]:
a=np.array([1,2,3])
a


array([1, 2, 3])

In [6]:
a=np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])


<class 'numpy.ndarray'>
(3,)
1 2 3


In [7]:
b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [8]:
print (b.shape)
print(b[0,0],b[0,1],b[1,1])

(2, 2)
1 2 4


In [10]:
c=np.array([[1,2],[3,4],[5,6]])
c



array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:

print(c[0,1],c[1,0],c[2,0],c[2,1])

2 3 5 6


In [12]:
d=np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
e2=np.ones((4,2))
print(e2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [14]:
f1=np.full((2,2),9)
print(f1)

[[9 9]
 [9 9]]


In [15]:
g=np.random.random((3,3))
print(g)


[[0.95734358 0.59441484 0.76479036]
 [0.98518713 0.47481821 0.62354254]
 [0.00180213 0.1289682  0.01885382]]


In [16]:
h1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(h1)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
i=h[:2,1:3]
print(i)

[[2 3]
 [6 7]]
