<a href="https://colab.research.google.com/github/AkhilGangan/MSC_FDS_530/blob/main/Fds_pracs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
import pandas as pd
a=np.array([1,2,3])
a
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
b=np.array([[1,2],[3,4]])
b
print (b.shape)
print(b[0,0],b[0,1],b[1,1])
c=np.array([[1,2],[3,4],[5,6]])
c
print(c[0,1],c[1,0],c[2,0],c[2,1])
d=np.zeros((2,3))
print(d)
e2=np.ones((4,2))
print(e2)
f=np.full((2,2),9)
print(f)
g=np.random.random((3,3))
print(g)
h1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(h1)
i=h[:2,1:3]
print(i)


<class 'numpy.ndarray'>
(3,)
1 2 3
(2, 2)
1 2 4
2 3 5 6
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[9 9]
 [9 9]]
[[0.20970214 0.50424113 0.71631168]
 [0.38994075 0.83795774 0.90201358]
 [0.69587978 0.51585759 0.36384443]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
